spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/campuscore}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  ai:
    openai:
      base-url: ${OPENROUTER_BASE_URL:https://openrouter.ai/api/v1}
      api-key: ${OPENROUTER_API_KEY:your-placeholder-key}
      chat:
        options:
          model: qwen/qwen3.5-plus-20260420

jwt:
  secret: ${JWT_SECRET:MTNEaVhTTFNNMXgwV0Vyeaj0Qlp2ZTRXd2xKbWxReVZ3YmNlUit0bUI1cEJxT0NnQkV5VVp5SnRrRnBFeVJZZS8=}
  expiration: 86400000 # 24 hours
  refresh-token:
    expiration: 604800000 # 7 days

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
